### ISSUE TITLE
how can set usdatepicker size？

### ISSUE THREAD

**Issue by xxdoc** [JoseMLiza/ucJLDatePicker#1]
Every time i open the demo.vbp ，change the form size ，closed ，than open the vbp，again，i found  ucJLDTPicker size is changes~~

It's weird~~

   udtItemsRangeButton(0).Caption = "Today"                'Hoy
    udtItemsRangeButton(1).Caption = "Current month"        'Este mes
    udtItemsRangeButton(2).Caption = "Last month"           'Mes pasado
    udtItemsRangeButton(3).Caption = "Last 90 days"         'Ultimos 90 d韆s
    udtItemsRangeButton(4).Caption = "Current year"         'Este A駉
    udtItemsRangeButton(5).Caption = "Last year"            'A駉 pasado
    '---
These buttons don't seem to work when I just click on an msgbox

but
    udtItemsActionButton(0).Caption = "Today"      

if  i click this ，can redraw  and show now day

**Comment by xxdoc** [comment]
Nice to see you update. I don't know if you have updated the above question

thanks

**Comment by JoseMLiza** [comment]
Hi xxdoc, sorry for the delay, I didn't see the first question.
First, thank you for your interest in this control.
Going back to the control, I need to know if you are using screen scaling
and if you could send me some images so that I can understand the situation
even more.

I will be waiting for more information.

**Comment by xxdoc** [comment]
you can see gif . I don't change any code. i drag the from size once. then you can see the control change big.

i cannot send gif to you、can give me a email address？
I didn't change any code, just changed the size of the form. Then run in IDE and colse the form . Run again and close again. You will find that the  the control will become larger and larger.

**Comment by xxdoc** [comment]
I used win10 125% 1920x1080 vb6 sp6

**Comment by JoseMLiza** [comment]
@xxdoc my email: josevliza@gmail.com

**Comment by xxdoc** [comment]
I sent gif .please check your email box

**Comment by xxdoc** [comment]
1.25=120/96  dpi  125%

may be restor the value to design if  value/12.5 ?

`Private Sub UserControl_WriteProperties(PropBag As PropertyBag)
   
    With PropBag
        Call .WriteProperty("BackColor", m_BackColor, &HFFFFFF)
        Call .WriteProperty("BackOpacity", m_BackOpacity, 100)
        Call .WriteProperty("Border", m_Border, True)
        Call .WriteProperty("BorderWidth", m_BorderWidth / 1.25, 1)
        Call .WriteProperty("BorderColor", m_BorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("BorderOpacity", m_BorderOpacity, 100)
        Call .WriteProperty("BorderPosition", m_BorderPosition, [Border Center])
        Call .WriteProperty("CornerTopLeft", m_CornerTopLeft/ 1.25, 0)
        Call .WriteProperty("CornerTopRight", m_CornerTopRight/ 1.25, 0)
        Call .WriteProperty("CornerBottomLeft", m_CornerBottomLeft/ 1.25, 0)
        Call .WriteProperty("CornerBottomRight", m_CornerBottomRight/ 1.25, 0)
        Call .WriteProperty("PaddingX", m_PaddingX/ 1.25, 20)
        Call .WriteProperty("PaddingY", m_PaddingY/ 1.25, 20)
        Call .WriteProperty("Shadow", m_Shadow, False)
        Call .WriteProperty("ShadowColor", m_ShadowColor, ColorConstants.vbBlack)
        Call .WriteProperty("ShadowSize", m_ShadowSize, 0)
        Call .WriteProperty("ShadowOpacity", m_ShadowOpacity, 50)
        Call .WriteProperty("ShadowOffsetX", m_ShadowOffsetX/ 1.25, 0)
        Call .WriteProperty("ShadowOffsetY", m_ShadowOffsetY/ 1.25, 0)
        Call .WriteProperty("ShowNumberWeek", m_ShowNumberWeek, True)
        Call .WriteProperty("ShowUseISOWeek", m_ShowUseISOWeek, True)
        Call .WriteProperty("SpaceGrid", m_SpaceGrid, 2)
        Call .WriteProperty("MouseToParent", m_MouseToParent, False)
        Call .WriteProperty("UseGDIPString", m_UseGDIPString, False)
        '--
        Call .WriteProperty("SinglePicker", m_SinglePicker, False)
        Call .WriteProperty("UseRangeValue", m_UseRangeValue, False)
        Call .WriteProperty("ShowRangeButtons", m_ShowRangeButtons, False)
        Call .WriteProperty("ShowTodayButton", m_ShowTodayButton, False)
        Call .WriteProperty("RightToLeft", m_RightToLeft, False)
        Call .WriteProperty("AutoApply", m_AutoApply, True)
        Call .WriteProperty("IsChild", m_IsChild, False)
        Call .WriteProperty("BackColorParent", m_BackColorParent, False)
        
        Call .WriteProperty("ColsPicker", m_ColsPicker, 0)
        Call .WriteProperty("NumberPickers", m_NumberPickers, IIF(Not m_SinglePicker, 2, 1))
        'Call .WriteProperty("ShowTimePicker", m_ShowTimePicker, False)                          'Para trabajar el timepicker.
        'Call .WriteProperty("UseTimePicker24Hrs", m_UseTimePicker24Hrs, False)                  'Para formato de 24 horas en timepicker.
        'Call .WriteProperty("TimerWithSecond", m_TimerWithSecond, False)                        'Para usar el timer hasta los segundos.
        Call .WriteProperty("MaxRangeDays", m_MaxRangeDays, 0)

        'Call .WriteProperty("AlwaysShowCalendars", m_AlwaysShowCalendars, True)
        Call .WriteProperty("LinkedCalendars", m_LinkedCalendars, True)
        
        Call .WriteProperty("Value", m_Value, Date)
        Call .WriteProperty("ValueStart", m_ValueStart, "")
        Call .WriteProperty("ValueEnd", m_ValueEnd, "")
        
        Call .WriteProperty("MinDate", m_MinDate, DateSerial(1601, 1, 1))
        Call .WriteProperty("MaxDate", m_MaxDate, DateSerial(9999, 12, 31))
        
        Call .WriteProperty("FirstDayOfWeek", m_FirstDayOfWeek, GetLocaleInfoAsLong(LOCALE_IFIRSTDAYOFWEEK))
        
        Call .WriteProperty("CountFreeDays", m_CountFreeDays, True)
        Call .WriteProperty("CountReservedDay", m_CountReservedDay, True)
        
        '---> De los botones de navegacion.
        Call .WriteProperty("ButtonNavBackColor", m_ButtonNavBackColor, &HFFFFFF)
        Call .WriteProperty("ButtonNavBorderWidth", m_ButtonNavBorderWidth/ 1.25, 1)
        Call .WriteProperty("ButtonNavBorderColor", m_ButtonNavBorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("ButtonNavCornerRadius", m_ButtonNavCornerRadius, 0)
        Call .WriteProperty("ButtonNavForeColor", m_ButtonNavForeColor, SystemColorConstants.vbButtonText)
        Call .WriteProperty("ButtonNavIsIcoFont", m_ButtonNavIsIcoFont, False)
        Call .WriteProperty("ButtonNavIcoFont", m_ButtonNavIcoFont, Ambient.Font)
        Call .WriteProperty("ButtonNavCharCodeBack", m_ButtonNavCharCodeBack, 0)
        Call .WriteProperty("ButtonNavCharCodeNext", m_ButtonNavCharCodeNext, 0)
        Call .WriteProperty("ButtonNavWidth", m_ButtonNavWidth / 1.25, 24)
        Call .WriteProperty("ButtonNavHeight", m_ButtonNavHeight / 1.25, 24)
        
        '---> De los botones de accion.
        Call .WriteProperty("ButtonsBackColor", m_ButtonsBackColor, &HFFFFFF)
        Call .WriteProperty("ButtonsBorderWidth", m_ButtonsBorderWidth / 1.25, 1)
        Call .WriteProperty("ButtonsBorderColor", m_ButtonsBorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("ButtonsCornerRadius", m_ButtonsCornerRadius, 5)
        Call .WriteProperty("ButtonsFont", m_ButtonsFont, Ambient.Font)
        Call .WriteProperty("ButtonsForeColor", m_ButtonsForeColor, SystemColorConstants.vbButtonText)
        Call .WriteProperty("ButtonsWidth", m_ButtonsWidth / 1.25, 24)
        Call .WriteProperty("ButtonsHeight", m_ButtonsHeight / 1.25, 24)

        '---> De los meses y a駉s
        Call .WriteProperty("MonthYearBackColor", m_MonthYearBackColor, &HFFFFFF)
        Call .WriteProperty("MonthYearBorderWidth", m_MonthYearBorderWidth / 1.25, 0)
        Call .WriteProperty("MonthYearBorderColor", m_MonthYearBorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("MonthYearCornerRadius", m_MonthYearCornerRadius, 0)
        Call .WriteProperty("MonthYearFont", m_MonthYearFont, Ambient.Font)
        Call .WriteProperty("MonthYearForeColor", m_MonthYearForeColor, SystemColorConstants.vbButtonText)

        '---> De las Semanas.
        Call .WriteProperty("WeekBackColor", m_WeekBackColor, &HFFFFFF)
        
        Call .WriteProperty("WeekBorderWidth", m_WeekBorderWidth / 1.25, 0)
        Call .WriteProperty("WeekBorderColor", m_WeekBorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("WeekCornerRadius", m_WeekCornerRadius, 0)
        Call .WriteProperty("WeekFont", m_WeekFont, Ambient.Font)
        Call .WriteProperty("WeekFontHeaderBold", m_WeekFontHeaderBold, True)
        Call .WriteProperty("WeekForeColor", m_WeekForeColor, SystemColorConstants.vbButtonText)
        Call .WriteProperty("WeekWidth", m_WeekWidth / 1.25, 26)
        Call .WriteProperty("WeekHeight", m_WeekHeight / 1.25, 24)

        '---> De los d韆s.
        Call .WriteProperty("DayBackColor", m_DayBackColor, &HFFFFFF)
        Call .WriteProperty("DayBorderWidth", m_DayBorderWidth / 1.25, 0)
        Call .WriteProperty("DayBorderColor", m_DayBorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("DayCornerRadius", m_DayCornerRadius, 0)
        Call .WriteProperty("DayFont", m_DayFont, Ambient.Font)
        Call .WriteProperty("DayHeaderFontBold", m_DayHeaderFontBold, True)
        Call .WriteProperty("DayHeaderForeColor", m_DayHeaderForeColor, SystemColorConstants.vbButtonText)
        Call .WriteProperty("DayHotColor", m_DayHotColor, SystemColorConstants.vbHighlight)
        Call .WriteProperty("DayForeColor", m_DayForeColor, SystemColorConstants.vbButtonText)
        Call .WriteProperty("DayOMForeColor", m_DayOMForeColor, SystemColorConstants.vbGrayText)
        Call .WriteProperty("DayFreeArray", m_DayFreeArray, Null)
        Call .WriteProperty("DayFreeForeColor", m_DayFreeForeColor, ColorConstants.vbRed)
        Call .WriteProperty("DayNowShow", m_DayNowShow, False)
        Call .WriteProperty("DayNowBorderWidth", m_DayNowBorderWidth / 1.25, 0)
        Call .WriteProperty("DayNowBorderColor", m_DayNowBorderColor, SystemColorConstants.vbActiveBorder)
        Call .WriteProperty("DayNowBackColor", m_DayNowBackColor, &HFFFFFF)
        Call .WriteProperty("DayNowForeColor", m_DayNowForeColor, SystemColorConstants.vbButtonText)
        
        'Mouse event (Los d韆s no tendran color para el mousedown)
        Call .WriteProperty("DayOverBackColor", m_DayOverBackColor, &H999999)
        Call .WriteProperty("DayOverForeColor", m_DayOverForeColor, &HFFFFFF)
        '--
        Call .WriteProperty("DaySelBetweenColor", m_DaySelBetweenColor, &HE5D7CA)
        'Call .WriteProperty("DaySelEndColor", m_DaySelEndColor, &H0)
        Call .WriteProperty("DaySelValuesColor", m_DaySelValuesColor, &HB06D00)
        Call .WriteProperty("DaySelForeColor", m_DaySelForeColor, &HFFFFFF)
        Call .WriteProperty("DaySelFontBold", m_DaySelFontBold, True)
        Call .WriteProperty("DaySelectionStyle", m_DaySelectionStyle, [Corner No Between])
        'Call .WriteProperty("DayShowHotItem", m_DayShowHotItem, True) ' Seimpre muestra el hot
        Call .WriteProperty("DaySaturdayForeColor", m_DaySaturdayForeColor, &H999999)
        Call .WriteProperty("DaySundayForeColor", m_DaySundayForeColor, &H999999)
        Call .WriteProperty("DayWidth", m_DayWidth / 1.25, 24)
        Call .WriteProperty("DayHeight", m_DayHeight / 1.25, 24)
     
        Call .WriteProperty("CallOut", m_CallOut, True)
        Call .WriteProperty("CallOutWidth", m_CallOutWidth / 1.25, 20)
        Call .WriteProperty("CallOutHight", m_CallOutHight / 1.25, 10)
        Call .WriteProperty("CallOutRightTriangle", m_CallOutRightTriangle, False)
        Call .WriteProperty("CallOutPosition", m_CallOutPosition, [Position Top])
        Call .WriteProperty("CallOutAlign", m_CallOutAlign, Middle)
        Call .WriteProperty("CallOutCustomPosPercent", m_CallOutCustomPosPercent, 0)
     
        'Call CreateShadow
    End With
   
End Sub`

**Comment by xxdoc** [comment]
Attribute VB_Name = "modDPI"
Option Explicit

Private Declare Function GetDC Lib "user32.dll" (ByVal hwnd As Long) As Long
Private Declare Function ReleaseDC Lib "user32.dll" (ByVal hwnd As Long, ByVal hdc As Long) As Long
Private Declare Function GetDeviceCaps Lib "gdi32" (ByVal hdc As Long, ByVal nIndex As Long) As Long
Private Const LOGPIXELSX        As Long = 88
'获取dpi比率
Public Function GetWindowsDPI() As Double
    Dim hdc As Long, LPX  As Double
    hdc = GetDC(0)
    LPX = CDbl(GetDeviceCaps(hdc, LOGPIXELSX))
    ReleaseDC 0, hdc

    If (LPX = 0) Then
        GetWindowsDPI = 1#
    Else
        GetWindowsDPI = LPX / 96#
    End If
End Function

**Comment by JoseMLiza** [comment]
Bro, try the new update

**Comment by xxdoc** [comment]
NOW work ok thanks

**Comment by xxdoc** [comment]
NOW work ok thanks

**Comment by xxdoc** [comment]
NOW work ok thanks
